#!/bin/bash
# 
# installer script for mkpkg
#  e.g. Call from PKGBUILD:  
#   do-install ${pkgdir}
# gene c (2022)
#
dest="$1"
self='mkpkg'

info="README.md CHANGELOG.md PKGBUILD"
infodir="/usr/share/${self}"

license="LICENSE"
licensedir="/usr/share/licenses/${self}"

# list apps without the ".py" or leave empty string
apps=("mkpkg")

sitedir=$(python -c "import site; print(site.getsitepackages()[0])")

if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
else
    # shared 
    rsync --mkpath -a ${info} ${dest}${infodir}
    rsync --mkpath -a ${license} ${dest}/${licensedir}/${license}

    /usr/bin/python -m installer --destdir="${dest}" dist/*.whl

    # link(s) in /usr/bin/
    if [ -v apps ] ; then
        /usr/bin/mkdir -p "${dest}/usr/bin"
        for app in ${apps[@]}
        do
            /usr/bin/ln -sf ${sitedir}/${self}/${app}.py "${dest}/usr/bin/${app}"
        done
    fi
    exit 0
fi
