#!/bin/bash
# 
# Can be useful to call from PKGBUILD install
#  e.g. do-install ${pkgdir}
# gene c (2022)

# target install dir
dest="$1"

info="README.md CHANGELOG.md LICENSE PKGBUILD"
sharedir="/usr/share/mkpkg"

sysdir=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
tdir="${dest}/${sysdir}"

if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
else
    # shared 
    rsync --mkpath -a ${info} ${dest}${sharedir}

    # application
    pip install --upgrade --compile dist/mkpkg-*.whl  -t ${tdir}

    # link in /usr/bin/mkpkg
    mkdir -p "${dest}/usr/bin"
    ln -sf ${sysdir}/mkpkg/mkpkg.py "${dest}/usr/bin/mkpkg"
    exit 0
fi
