py.install_sources(
  'build_makepkg.py',
  'build.py',
  'check_deps.py',
  'class_config.py',
  'class_mkpkg.py',
  'class_msg.py',
  'color_pick.py',
  'dep_vers.py',
  'elf_utils.py',
  'file_tools.py',
  '__init__.py',
  '_mkpkg_base.py',
  'pacman.py',
  'pkgbuild.py',
  'soname_deps.py',
  'soname_info.py',
  'soname.py',
  'soname_rebuild.py',
  'split_deps.py',
  'text.py',
  'toml.py',
  'tools.py',
  'version_compare.py',
  'version.py',
  subdir: 'mkpkg_mod/lib'
)
