#!/usr/bin/bash
#
# Run static code checkers
#

export PYTHONPATH=$(/usr/bin/realpath ./src)
mod="src/mkpkg_mod"

/usr/bin/pylint $mod/*.py $mod/*/*.py
/usr/bin/pycodestyle --max-line-length=110 $mod/*.py $mod/*/*.py
/usr/bin/mypy --check-untyped-defs --follow-untyped-imports $mod

