#!/usr/bin/bash
#
# Run mypy checker
#

echo "Running mypy:"
PYTHONPATH=src/mkpkg mypy --check-untyped-defs --follow-untyped-imports src/mkpkg/

cd src/mkpkg

echo "Running pylint:"
PYTHONPATH=. pylint *.py lib/*.py

echo "Running pycodestyle:"
PYTHONPATH=. pycodestyle *.py --max-line-length=110 lib/*.py
